name: easy_count_timer
description: It is a simple customizable timer for counting [`up`/`down`] a given time with any Custom TextStyle.
version: 0.0.2
homepage: https://github.com/aissat/easy_count_timer
repository: https://github.com/aissat/easy_count_timer
issue_tracker: https://github.com/aissat/easy_count_timer/issues

environment:
  sdk: ">=3.1.1 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
